services:
    frontend:
        build: ./frontend
        ports:
            - 3000:3000
        environment:
            # NODE_ENV: production
            NODE_ENV: development
            CHOKIDAR_USEPOLLING: true
            NEXT_PUBLIC_API_URL: /api/v1
        volumes:
            - ./frontend:/app
            - /app/node_modules
        restart: unless-stopped

    api:
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: always
        environment:
            DB_HOST: postgres
            DB_PORT: 5432
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
            DB_NAME: expenses_db
        ports:
            - 8080:80
        volumes:
            - ./backend:/app # DEV only
        depends_on:
            - postgres

    postgres:
        image: postgres:15.8
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: expenses_db
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: always
        ports:
            - 5432:5432

    reverse_proxy:
        image: nginx:1.29.4
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        restart: always
        ports:
            - "80:80"
        depends_on:
            - api
            - frontend

volumes:
    postgres-data:
